spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_mvc
    username: root
    password: 08012005

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true